# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026 Saúl Fernández García <https://github.com/saulfernandezgarcia>
#

# Build plugin_a.ko

obj-m := sfgplugina.o

sfgplugina-objs = plugin_a.o

ccflags-y := -I$(src)/../../include