# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026 Saúl Fernández García <https://github.com/saulfernandezgarcia>
#

# Build sfgcore.ko

obj-m := sfgcore.o

sfgcore-objs += core.o core_debugfs.o

ccflags-y := -I$(src)/../include