# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026 Saúl Fernández García <https://github.com/saulfernandezgarcia>
#

# Build sfgcheck_a.ko

obj-m := sfgcheck_a.o

sfgcheck_a-objs = check_a.o

ccflags-y := -I$(src)/../../include