# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026 Saúl Fernández García <https://github.com/saulfernandezgarcia>
#

# Build plugin_b

obj-m := sfgpluginb.o

sfgpluginb-objs = plugin_b.o

ccflags-y := -I$(src)/../../include