# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026 Saúl Fernández García <https://github.com/saulfernandezgarcia>
#

# Build sfgplugin_c

obj-m := sfgplugin_c.o

sfgplugin_c-objs = plugin_c.o

ccflags-y := -I$(src)/../../include