# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2026 Saúl Fernández García <https://github.com/saulfernandezgarcia>
#

# Build sfgcheck_b

obj-m := sfgcheck_b.o

sfgcheck_b-objs = check_b.o

ccflags-y := -I$(src)/../../include